version: '2'
services:
  rates-service:
    image: rates
    restart: unless-stopped
    depends_on:
      - postgres
    command: bash -c "sh  /go/src/github.com/morrah77/rates/bin/main --scrap-url https://wex.nz/api/3 --scrap-intervall 2s --listen-addr :8080 --api-path /rates/v0 --storage postgres --dsn \"host=postgres port=5432 user=postgres password=changeit dbname=main sslmode=disable\""
  postgres:
    image: postgres:9.6
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeit
      POSTGRES_DB: main
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local